---
- name: Install fluentd plugin(s)
  shell: |
    /usr/sbin/td-agent-gem install {{ item }} --no-document
  with_items: "{{ fluentd_extra_plugins }}"
  when: fluentd_extra_plugins | length > 0

- name: Copy Fluentd configuration
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
  notify: restart fluentd

- name: Add Fluentd system user to groups
  user:
    name: "{{ fluentd_system_user }}"
    groups: "{{ fluentd_monitoring_groups }}"
    append: true
  notify: restart fluentd
