---
- name: Install | update GEM_HOME in {{ fluentd_system_environment_file }}
  ansible.builtin.lineinfile:
    dest: "{{ fluentd_system_environment_file }}"
    state: present
    regexp: "^GEM_HOME="
    line: 'GEM_HOME="{{ fluentd_gem_home_directory }}"'
  tags:
    - fluentd-install-update-gem-home
    - fluentd-install

- name: Install | update GEM_PATH in {{ fluentd_system_environment_file }}
  ansible.builtin.lineinfile:
    dest: "{{ fluentd_system_environment_file }}"
    state: present
    regexp: "^GEM_PATH="
    line: 'GEM_PATH="{{ fluentd_gem_path_directory }}"'
  tags:
    - fluentd-install-update-gem-path
    - fluentd-install

## Install Ruby >= 2.4 on your local environment. In addition, install ruby-dev package via Package Manager to build native extension gems.
- name: Install | ruby packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  environment:
    GEM_PATH: "{{ fluentd_lib_directory }}"
    GEM_HOME: "{{ fluentd_lib_directory }}"
  tags:
    - fluentd-install-ruby-packages
    - fluentd-install
  with_items:
    - ruby
    - ruby-dev
    - gcc

- name: Install | add fluentd gem(s)
  ansible.builtin.shell: |
    gem install {{ item.name }} -v {{ item.version | default('>=0') | quote }}  --no-document
  with_items: "{{ fluentd_required_gems }}"
  environment:
    GEM_PATH: "{{ fluentd_lib_directory }}"
    GEM_HOME: "{{ fluentd_lib_directory }}"
  changed_when: true
  when: fluentd_required_gems | length > 0
  tags:
    - fluentd-install-add-plugin
    - fluentd-install

- name: Install | fluentd {{ fluentd_version }}
  ansible.builtin.shell: |
    gem install fluentd -v {{ fluentd_version }} --no-document
  environment:
    GEM_PATH: "{{ fluentd_lib_directory }}"
    GEM_HOME: "{{ fluentd_lib_directory }}"
  changed_when: true
  tags:
    - fluentd-install-fluentd
    - fluentd-install
