---
- name: Install fluentd
  ansible.builtin.include_tasks: install.yml
  tags:
    - fluentd-install
    - fluentd

- name: Setup-legacy
  ansible.builtin.include_tasks: setup-legacy.yml
  when: fluentd_s3_bucket_legacy
  tags:
    - fluentd-setup-legacy
    - fluentd-setup
    - fluentd

- name: Setup
  ansible.builtin.include_tasks: setup.yml
  when: not fluentd_s3_bucket_legacy
  tags:
    - fluentd-setup
    - fluentd

- name: Setup-jemalloc
  ansible.builtin.include_tasks: setup-jemalloc.yml
  tags:
    - fluentd-setup-jemalloc
    - fluentd

- name: Configure fluentd
  ansible.builtin.include_tasks: configure.yml
  tags:
    - fluentd-configure
    - fluentd
