---
- name: Set-up | ensure exists  {{ fluentd_system_group }}
  ansible.builtin.group:
    name: "{{ fluentd_system_group }}"
    state: present
  tags:
    - fluentd-setup-create-group
    - fluentd-setup

- name: Set-up | create user {{ fluentd_system_user }}
  ansible.builtin.user:
    name: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
    shell: /sbin/nologin
    create_home: false
    state: present
  tags:
    - fluentd-setup-create-user
    - fluentd-setup

- name: Set-up | create fluentd config directory
  ansible.builtin.file:
    path: "{{ fluentd_conf_directory }}"
    state: directory
    mode: '0740'
    owner: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
  tags:
    - fluentd-setup-create-config-directory
    - fluentd-setup

- name: Set-up | create fluentd extra config directory {{ fluentd_extra_config_file_dir }}
  ansible.builtin.file:
    path: "{{ fluentd_extra_config_file_dir }}"
    state: directory
    mode: '0740'
    owner: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
  tags:
    - fluentd-setup-create-config-directory
    - fluentd-setup

- name: Set-up | create fluentd directory {{ fluentd_lib_directory }}
  ansible.builtin.file:
    path: "{{ fluentd_lib_directory }}"
    state: directory
    mode: '0750'
    owner: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
  tags:
    - fluentd-setup-create-lib-directory
    - fluentd-setup

- name: Set-up | create fluentd log config directory
  ansible.builtin.file:
    path: "{{ fluentd_log_directory }}"
    state: directory
    mode: '0740'
    owner: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
  tags:
    - fluentd-setup-create-log-directory
    - fluentd-setup

- name: Set-up | create fluentd conf file(s)
  ansible.builtin.copy:
    dest: "{{ fluentd_extra_config_file_dir }}/{{ item.name }}.conf"
    content: "{{ item.conf }}"
    owner: "{{ fluentd_system_user }}"
    group: "{{ fluentd_system_group }}"
    mode: 0640
  with_items: "{{ fluentd_configurations }}"
  tags:
    - fluentd-setup-create-conf-file
    - fluentd-setup
