---
- name: Converge
  hosts: all
  roles:
    - role: "onaio.fluentd"
      fluentd_monitoring_groups:
        - adm
      fluentd_configurations:
        - name: nginx-access-log
          conf: |
            <source>
              @type tail
              format nginx
              pos_file /var/log/fluent/tmp/nginx-access.log.pos
              tag nginx.access
              path /var/log/nginx/access.log
            </source>
            <match nginx.access>
              @type file
              path /var/log/fluent/nginx-access
            </match>
