---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install gpg
      apt:
        name: gpg
        update_cache: true
        state: present

  roles:
    - role: "onaio.fluentd"
      fluentd_monitoring_groups:
        - adm
      fluentd_configurations:
        - name: nginx-access-log
          conf: |
            <source>
              @type tail
              format nginx
              pos_file /var/log/fluent/tmp/nginx-access.log.pos
              tag nginx.access
              path /var/log/nginx/access.log
            </source>
            <match nginx.access>
              @type file
              path /var/log/fluent/nginx-access
            </match>
