---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install gpg
      apt:
        name: gpg
        update_cache: true
        state: present

  roles:
    - role: ansible-fluentd
      fluentd_monitoring_groups:
        - adm
      fluentd_log_paths:
        - tag: nginx
          path: /var/log/nginx/*
      fluentd_aws_key_id: test_key_id
      fluentd_aws_secret_key: test_secret_key
      fluentd_s3_bucket: test-bucket
      fluentd_s3_region: eu-west-1
      fluentd_server_owner: ona
      fluentd_server_environment: test
      fluentd_server_private_ipv4_address: "10.160.0.158"
