---
# This is a playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Check td-agent service is enabled
      command: systemctl is-enabled td-agent.service
      register: _td_agent_service_is_enabled_output

    - name: Check td-agent service is active
      command: systemctl is-active td-agent.service
      register: _td_agent_service_is_active_output

    - name: Check td-agent flush logs service is enabled
      command: systemctl is-enabled td-agent-flush-logs.service
      register: _flush_logs_service_is_enabled_output

    - name: Verify that the services are OK
      assert:
        that:
          - _td_agent_service_is_enabled_output.rc == 0
          - _td_agent_service_is_active_output.rc == 0
          - _flush_logs_service_is_enabled_output.rc == 0
